on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "index.html"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SSH
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          first_ssh: |
            rm ./home/index.html
            rm -rf ./home/src/css/**
            rm -rf ./home/src/js/**

          scp: |
            ./src/css/* => ./home/src/css/
            ./src/js/* => ./home/src/js/
            ./index.html => ./home/
